config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :posts do
    resources :comments, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  body       :text
#  post_id    :integer
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#

class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  validates :description, length: { minimum: 250 }
  validates :title, :description, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts
  has_many :comments
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end
  def create
    @comment = Comment.new(comment_params)
    @comment.post_id = params[:post_id]
    @comment.user_id = current_user.id
    @comment.save
    redirect_to post_path(params[:post_id])
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:success] = "Tu Post ha sido creado"
      redirect_to root_path
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  def show
    @comment = @post.comments.new
  end
  def edit

  end
  def update
    @post.update_attributes(post_params)
    if @post.save
      flash[:success] = "Tu Post ha sido creado"
      redirect_to post_path(@post.id)
    end
  end


  private
  def post_params
    params.require(:post).permit(:title, :description)
  end
  def find_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    renderer = Redcarpet::Render::HTML.new(:no_links => true, :hard_wrap => true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SuperBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="/assets/markitup/skins/markitup/style.css">
    <!--  markItUp! toolbar skin -->
    <link rel="stylesheet" type="text/css" href="/assets/markitup/sets/markdown/style.css">
    <!-- markItUp! -->
    <script type="text/javascript" src="/assets/markitup/jquery.markitup.js"></script>
    <!-- markItUp! toolbar settings -->
    <script type="text/javascript" src="/assets/markitup/sets/markdown/set.js"></script>
  </head>

  <body>
    <nav class="navbar">
      <div class="container">
          <div class="navbar-header ">
            <a class="navbar-brand logo" href="/">Super Blog</a>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li ><%= link_to "Nuevo Post", new_post_path, remote: true %></li>
              <li ><%= link_to "Log out ", destroy_user_session_path, method: "delete" %></li>
              <li><a href=""><%=current_user.email%></a></li>
            <% else %>
              <li ><a href="/users/sign_in">Log In</a></li>
              <li><a href="/users/sign_up">Sing Up</a></li>
            <%end%>
          </ul>
        </div>
        </div>
      </nav>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div class="alerta">
        </div>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title"><%= title %></h3>
      </div>
      <%= form_for @post, remote: true do |f| %>
      <div class="modal-body">
        <div class="form-group">
          <%= f.text_field :title, placeholder: "Titulo", class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.text_area :description, placeholder:"Descrpción", class:"form-control markItUp", rows:"5" %>
        </div>
      </div>
      <div class="modal-footer">
        <%= f.submit class: "btn btn-primary btn-block" %>
      </div>
    <% end %>
  </div>
</div>
</div>
<script type="text/javascript" >

  $(document).ready(function() {
  $(".markItUp").markItUp(mySettings);
  });
</script>

app/views/posts/_row.html.erb
<div class="panel panel-default public" id="<%= post.id %>">
  <div class="panel-body">
    <h3 class="panel-title row">
      <div class="gravatar round-image-50 col-md-2" style="background:transparent url(<%= gravatar_image_url(post.user.email.gsub('spam', 'mdeering'), size: 50) %>) "></div>
      <div class="col-md-10 align-self-center">
        <%=post.title %>
            <hr>
      </div>
    </h3>
    <p><%= markdown truncate(post.description, :length => 250) %></p>
  </div>
  <div class="panel-footer">
    <p>Por: <%=post.user.email%>
      <span class="text-muted"> | Realizado hace: <%=((post.created_at-DateTime.now)*0.0000115740).round.abs%>dias </span>
      <% if current_user %>
        <% if current_user.id == post.user.id %>
          <span class="borrar"><%= link_to "<span class='glyphicon glyphicon-pencil' aria-hidden='true'></span>".html_safe, edit_post_path(post.id), class:"btn btn-sm btn-info",remote: true %></span>
          <span class="borrar"><%= link_to "<span class='glyphicon glyphicon-trash' aria-hidden='true'></span>".html_safe, post, method: :delete, data: { confirm: 'Estas seguro de borrar el post?' }, class:"btn btn-sm btn-danger" %></span>
        <% end %>
      <% end %>
      <span class="borrar"><%= link_to "Ver más",post_path(post), class:"btn btn-sm btn-default" %></span>
    </p>
  </div>
</div>

app/views/posts/create.js.erb
<% if @post.errors.empty? %>
  // add the row to the table, show alert and hide modal
  $('.post').append(' <%= j render "row", post: @post %>');
  $('.alert-success').html("El producto ha sido creado con éxito").show();
  // $('.inicio').html('<div class="alert alert-success" role="alert"><p style="text-align:center">Post Creado</p></div>');
  $('#myModal').modal('hide');
  $("[data-dismiss=modal]").trigger({ type: "click" });
  // window.location.reload(true);
<% else %>
  // show first error
  // alert('<%= @post.errors.full_messages[0] %>');
  $('#myModal .modal-header .alerta').html('<div class="alert alert-danger" role="alert"><p style="text-align:center"><%= @post.errors.full_messages[0] %></p></div>')
<% end %>

app/views/posts/edit.js.erb
$('<%= j render "form", title: "Editar Post" %>').modal();

app/views/posts/index.html.erb
<% flash.each do |key, message| %>
    <div class="alert alert-<%= key %>" role="alert"><p style="text-align:center"><%= message %></p></div>
<% end %>
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="post">
          <% if @posts.count > 0  %>
            <% @posts.each do |p| %>
              <%= render "row", post: p %>
            <%end %>
          <%else%>
            <h2>Aun no hay ningun post :(</h2>
          <%end %>
        </div>
      </div>
    </div>
  </div>

app/views/posts/new.js.erb
$('<%= j render "form", title: "Nuevo Post" %>').modal();

app/views/posts/show.html.erb
<div class="container">
  <% flash.each do |key, message| %>
      <div class="alert alert-<%= key %>" role="alert"><p style="text-align:center"><%= message %></p></div>
  <% end %>
  <div class="jumbotron">
      <h1><%=@post.title%></h1>
      <div class="container post">
        <p><%= markdown  @post.description %></p>
        <hr>
      </div>
      <% if current_user %>
        <% if current_user.id == @post.user.id %>
          <span class="borrar"><%= link_to " Editar <span class='glyphicon glyphicon-pencil' aria-hidden='true'></span>".html_safe, edit_post_path(@post.id), class:"btn btn-sm btn-default",remote: true %></span>
        <% end %>
      <% end %>
  </div>
  <div class="container">
    <% @post.comments.each do |com| %>
      <% if com.id == nil %>
      <%else %>
        <div class="row">
          <div class="col-sm-1">
            <div class="thumbnail">
              <%= image_tag gravatar_image_url(com.user.try(:email)), alt: 'gravatar image', class:"img-responsive user-photo" %>
            </div>
          </div>
          <div class="col-sm-10">
            <div class="panel panel-default">
              <div class="panel-heading">
              <strong><%=com.user.try(:email)%>
              </div>
              <div class="panel-body">
              <%= markdown com.body %>
              </div>
            </div>
          </div>
        </div>
      <%end %>
    <%end %>
    <hr>
    <% if current_user %>
     <div id = "comentarios">
       <%= form_for @comment, url: post_comments_path(@post)  do | f| %>
           <div>
             <%= f.text_area :body, placeholder:"Agregar comentario", class:"coment markItUp" %>
           </div>
           <%= f.submit "Comentar", class: "btn btn-sm btn-default boton"%>
       <% end %>
     </div>
    <% end %>
  </div>
</div>
<script type="text/javascript" >

  $(document).ready(function() {
  $(".markItUp").markItUp(mySettings);
  });
</script>

app/views/posts/update.js.erb
<% if @post.errors.empty? %>
  // add the row to the table, show alert and hide modal
  $('.post').append(' <%= j render "row", post: @post %>');
  $('.alert-success').html("El producto ha sido modificado con éxito").show();
  // $('.inicio').html('<div class="alert alert-success" role="alert"><p style="text-align:center">Post Creado</p></div>');
  $('#myModal').modal('hide');
  $("[data-dismiss=modal]").trigger({ type: "click" });
  // window.location.reload(true);
<% else %>
  // show first error
  // alert('<%= @post.errors.full_messages[0] %>');
  $('#myModal .modal-header .alerta').html('<div class="alert alert-danger" role="alert"><p style="text-align:center"><%= @post.errors.full_messages[0] %></p></div>')
<% end %>